### PR TITLE
Add sentry dependency

### PR DESCRIPTION
**Pull request by denvaar**
I'm not sure if there is any other configuration you would like me to add.

### CODE REVIEW

**Comment by rfunix** [comment]
Hi @denvaar , thanks for your contribution !

I think it's interesting, we try to catch exceptions that can occur with our processes.

I think we could implement the [Logger Backend](https://github.com/getsentry/sentry-elixir#capture-crashed-process-exceptions) in our supervisors.

**Comment by denvaar** [comment]
Ok, I will work on this some more.

**Comment by denvaar** [comment]
@rfunix I've added the logger backend. Do we need to also add Sentry configuration, or is that supposed to go in the applications which use this library?

**Comment by rfunix** [comment]
Hi @denvaar , it's fine. Thanks !

**Pull request merged**
